title: NCSA Genomics
description: 
show_downloads: true
comments: true
logo_url: git-wiki/assets/images/sample.jpg
google_analytics:
git_branch: http://cmwr2012.cee.illinois.edu/images/ncsa_vertical.png
theme: 
use_github_wiki: false
use_prose_io: true
google_cse_token: 007197903287787072094:8rbvkeqo6qw
custom_sidebar: true
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
