title: NCSA Genomics
description: 
show_downloads: true
comments: true
logo_url: git-wiki/assets/images/Genomics_Cat.PNG
google_analytics:
git_branch: gh-pages
theme: 
use_github_wiki: false
use_prose_io: true
google_cse_token: 007197903287787072094:8rbvkeqo6qw
custom_sidebar: true
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
