title: NCSA - Genomics
description: 
show_downloads: true
git_branch: master
logo_url: http://cmwr2012.cee.illinois.edu/images/ncsa_vertical.png
google_analytics:
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: false
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
